name: Metrics
on:
  # Schedule daily updates at midnight UTC
  schedule: [{cron: "0 0 * * *"}]
  # Run workflow manually from the Actions tab
  workflow_dispatch:
  # Run on push to main branch
  push: {branches: ["main"]}
jobs:
  metrics-overview:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: davideak22
          template: classic
          base: header, activity, community, repositories, metadata
          plugins_errors_fatal: no
          plugin_languages: yes
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_indepth: no
          plugin_lines: yes
          plugin_lines_sections: base
          config_timezone: Asia/Dubai
          filename: assets/metrics.svg

  metrics-habits:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: davideak22
          template: classic
          base: ""
          plugins_errors_fatal: no
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          config_timezone: Asia/Dubai
          filename: assets/metrics-habits.svg
